export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_WHISHLIST = 'ADD_TO_WHISHLIST';
export const REMOVE_FROM_WHISHLIST = 'REMOVE_FROM_WHISHLIST';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';
export const FETCH_USERS_DATA = 'FETCH_USERS_DATA';
export const FETCH_PRODUCTS_QTY = 'FETCH_PRODUCTS_QTY';